# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    apt-get update
    apt-get install python3
    python --version
    python -m pip install --upgrade pip
    python -m pip install requests
  displayName: 'installing python'
        
- script: |
    python flinko.py
  displayName: 'flinko test'
